security:
    encoders:
#        FOS\UserBundle\Model\UserInterfase: sha512
        Blog\UserBundle\Entity\FOSUser: sha512
        Blog\UserBundle\Security\User\WebserviceUser: sha512

    role_hierarchy:
        ROLE_ADMIN:         ROLE_USER
        ROLE_SUPER_ADMIN:   ROLE_ADMIN

    providers:
        in_memory:
            memory: ~
        fos_userbundle:
            id: fos_user.User_provider.username
        webservice:
            id: webservice_user_provider

    firewalls:
        main:
            pattern:    ^/
            form_login:
                provider:       fos_userbundle
                csrf_provider:  form.csrf_provider
            logout:     true
            anonymous:  true
#        dev:
#            pattern: ^/(_(profiler|wdt)|css|images|js)/
#            security: false
#
#        default:
#            anonymous: ~

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }
