home:
    path:       /
    defaults:   { _controller: BlogNewsBundle:Index:index }

contact:
    path:       /contact
    defaults:   { _controller: BlogNewsBundle:Index:contact }

advert_form:
    path:       /advert_form
    defaults:   { _controller: BlogNewsBundle:Index:advertForm }

createAdvertisement:
    path:       /create_advert
    defaults:   { _controller: BlogNewsBundle:Index:createAdvertisement }

service:
    path:       /service
    defaults:   { _controller: BlogNewsBundle:Service:index }

sendEmail:
    path:       /send
    defaults:   { _controller: BlogNewsBundle:Service:send }

all_comments:
    path:       /comment
    defaults:   { _controller: BlogNewsBundle:Service:comment }
