home:
    path:       /
    defaults:   { _controller: BlogNewsBundle:Index:index }

contact:
    path:       /contact
    defaults:   { _controller: BlogNewsBundle:Index:contact }

adverts:
    path:       /adverts
    defaults:   { _controller: BlogNewsBundle:Index:adverts }

show_advert:
    path:       /show/{slug}
    defaults:   { _controller: BlogNewsBundle:Index:showAdvert }

new_advert:
    path:       /advert/new
    defaults:   { _controller: BlogNewsBundle:Index:newAdvert }

update_advert:
    path:       /advert/{id}/update
    defaults:   { _controller: BlogNewsBundle:Index:updateAdvert }
    requirements:
        id: \d+

delete_advert:
    path:       /advert/{id}/delete
    defaults:   { _controller: BlogNewsBundle:Index:deleteAdvert }
    requirements:
        id: \d+

service:
    path:       /service
    defaults:   { _controller: BlogNewsBundle:TestServices:index }

sendEmail:
    path:       /send
    defaults:   { _controller: BlogNewsBundle:TestServices:send }

all_comments:
    path:       /comment
    defaults:   { _controller: BlogNewsBundle:TestServices:comment }

categories:
    path:       /categories
    defaults:   { _controller: BlogNewsBundle:Category:index }

category_show:
    path:       /categories/{slug}
    defaults:   { _controller: BlogNewsBundle:Category:showCategory }

message:
    path:       /message/{_locale}
    defaults:   { _controller: BlogNewsBundle:Index:message }
    requirements:
        _locale: en|fr|ua
